---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: candlepin
  namespace: theforeman-org-tenant
spec:
  displayName: candlepin
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
  name: candlepin-develop
  namespace: theforeman-org-tenant
spec:
  application: candlepin
  componentName: candlepin-develop
  containerImage: quay.io/foreman/candlepin-stage
  source:
    git:
      context: images/candlepin
      dockerfileUrl: Containerfile
      revision: master
      url: https://github.com/theforeman/candlepin-oci-images.git
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/application: candlepin
    appstudio.redhat.com/component: candlepin-develop
  name: candlepin-develop
  namespace: theforeman-org-tenant
spec:
  image:
    name: theforeman/candlepin
    visibility: public
