---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: foreman
  namespace: theforeman-org-tenant
spec:
  displayName: foreman
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta","bundle":"latest"}'
    git-provider: github
    git-provider-url: https://github.com
  name: foreman-develop
  namespace: theforeman-org-tenant
spec:
  application: foreman
  componentName: foreman-develop
  containerImage: quay.io/foreman/foreman-stage
  source:
    git:
      context: images/foreman
      dockerfileUrl: Containerfile
      revision: master
      url: https://github.com/theforeman/foreman-oci-images.git
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  labels:
    appstudio.redhat.com/application: foreman
    appstudio.redhat.com/component: foreman-develop
  name: foreman-develop
  namespace: theforeman-org-tenant
spec:
  image:
    name: theforeman/foreman
    visibility: public
